# theme
remote_theme: mmistakes/minimal-mistakes@4.21.0
minimal_mistakes_skin: default

# site
locale: en-US
title: VSGAN Documentation
masthead_title: rlaPHOENiX / VSGAN
subtitle: Documentation
title_separator: "-"
name: PHOENiX
description: Documentation for VSGAN - VapourSynth Single Image Super-Resolution Generative Adversarial Network (GAN).
url: https://rlaphoenix.github.io/VSGAN
repository: rlaPHOENiX/VSGAN
breadcrumbs: false
words_per_minute: 200
atom_feed:
  show: false

# search
search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id: A8NT4DVY7Q
  index_name: vsgan
  search_only_api_key: b04af9550fe986069923251437b30c6f
  powered_by: true

# site footer
footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/rlaPHOENiX/VSGAN

# social sharing
twitter:
  username: rlaPHOENiX
social:
  type: Person
  name: rlaPHOENiX
  links:
    - https://twitter.com/rlaPHOENiX

# reading files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: md

# conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# markdown processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# collections
collections:
  docs:
    output: true
    permalink: /:path/

# defaults
defaults:
  - scope:
      path: ""
    values:
      comments: false
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: true
      author_profile: false
      share: true
      sidebar:
        nav: docs

# sass/scss
sass:
  sass_dir: _sass
  style: compressed

# outputting
timezone: Europe/Dublin

# plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
